#!/bin/sh
# shellcheck disable=SC2086,SC2181

## By Sanjay Pavan <tsppavan7@gmail.com>
## License : MIT

# Prevent root user from running the script
if [ "$(id -u)" = 0 ]; then
    dialog --title "Warning" --infobox "SLDM should not be run as root user" 0 0
    exit 1
fi

xsessions_folder="/usr/share/xsessions"
xinit_file="$HOME/.local/share/xinitrc"
count_lines=$(find ${xsessions_folder} -name "*.desktop" -type f | sort | wc -l)

# Can't use the below commented line of code bcuz it is not POSIX and seq is not used and being replaced by awk
#DIALOG_STUFF=$(paste -d ' ' <(seq 1 $count_seq) <(find $xsessions_folder -maxdepth 2 -name "*.desktop" -type f | sort | sed "s|$xsessions_folder/||" | sed 's/.desktop//') | paste -sd ' ')
fake_array () {
paste -d ' ' /dev/fd/3 3<<-EOF /dev/fd/4 4<<-EOF
$(awk -v MYEND="${count_lines}" 'BEGIN { for(i=1;i<=MYEND;i++) print i }')
EOF
$(find $xsessions_folder -name "*.desktop" -type f | sort | sed "s|$xsessions_folder/||" | sed 's/\.desktop//')
EOF
}

DIALOG_STUFF=$(fake_array | paste -sd ' ')

# The dialog box
CHOICE=$(dialog --title "SLDM" --menu "Choose one" 0 0 9 ${DIALOG_STUFF} 3>&2 2>&1 1>&3)

# If dialog exits with OK
# I know that this is totally stupid to check exit code with 0 but if you can, please help me
if [ $? -eq 0 ]
then
    chosen_wm_file=$(find ${xsessions_folder} -name "*.desktop" -type f | sort | sed -n ${CHOICE}p)
    extract_exec=$(grep '^Exec' ${chosen_wm_file} | tail -1 | sed 's/^Exec=//' | sed 's/%.//' | sed 's/^"//g' | sed 's/" *$//g')
    echo exec ${extract_exec} > ${xinit_file}
    startx ${xinit_file}
else
    echo "User cancelled" && exit 1
fi
